version: '3.9'

services:
  web:
    build: .
    ports:
      - 3333:3333
    volumes:
      - ./:/app
    container_name: pizzaria_api_app
    networks:
      - pizzaria_network
    entrypoint: npm start
  
  database:
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - ./.database/:/var/lib/postgresql/data
    container_name: pizzaria_api_database
    networks:
      - pizzaria_network
    environment:
      - POSTGRES_PASSWORD=pizzaria
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pizzaria

networks:
  pizzaria_network:
    driver: bridge